# Generated by Django 5.2.14 on 2026-05-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kategori', models.CharField(max_length=10, unique=True)),
                ('nama_kategori', models.CharField(max_length=50)),
                ('level_urgensi', models.CharField(choices=[('Rendah', 'Rendah'), ('Sedang', 'Sedang'), ('Tinggi', 'Tinggi'), ('Kritis', 'Kritis')], default='Sedang', max_length=20)),
                ('deskripsi', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15)),
                ('grup_pengguna', models.CharField(choices=[('Admin', 'Admin'), ('HRD', 'HRD'), ('Staff', 'Staff')], default='Staff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id_catatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pegawai', models.CharField(max_length=100)),
                ('jenis_aksi', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Tambah Dokumen', 'Tambah Dokumen'), ('Edit Dokumen', 'Edit Dokumen'), ('Hapus Dokumen', 'Hapus Dokumen'), ('Tambah Pengguna', 'Tambah Pengguna'), ('Edit Pengguna', 'Edit Pengguna'), ('Hapus Pengguna', 'Hapus Pengguna')], max_length=50)),
                ('referensi_dokumen', models.CharField(blank=True, max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('waktu_catatan', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pegawai')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-waktu_catatan'],
            },
        ),
        migrations.CreateModel(
            name='DokumenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_referensi', models.CharField(max_length=20, unique=True)),
                ('judul_dokumen', models.CharField(max_length=100)),
                ('file_lampiran', models.FileField(upload_to='dokumen/')),
                ('tanggal_berlaku', models.DateField()),
                ('tanggal_kedaluwarsa', models.DateField()),
                ('status_dokumen', models.CharField(default='Aktif', max_length=20)),
                ('jenis_dokumen', models.CharField(choices=[('KTP', 'KTP'), ('SIM', 'SIM'), ('Paspor', 'Paspor'), ('Sertifikat Kerja', 'Sertifikat Kerja'), ('Kartu Identitas Karyawan', 'Kartu Identitas Karyawan'), ('Surat Izin Kerja', 'Surat Izin Kerja'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_staff', to='core.pegawai')),
            ],
            options={
                'verbose_name': 'Dokumen Staff',
                'verbose_name_plural': 'Dokumen Staff',
            },
        ),
        migrations.CreateModel(
            name='DokumenHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_referensi', models.CharField(max_length=20, unique=True)),
                ('judul_dokumen', models.CharField(max_length=100)),
                ('file_lampiran', models.FileField(upload_to='dokumen/')),
                ('tanggal_berlaku', models.DateField()),
                ('tanggal_kedaluwarsa', models.DateField()),
                ('status_dokumen', models.CharField(default='Aktif', max_length=20)),
                ('departemen', models.CharField(default='HRD', max_length=50)),
                ('jenis_dokumen', models.CharField(choices=[('Kontrak Kerja', 'Kontrak Kerja'), ('Surat Pengangkatan', 'Surat Pengangkatan'), ('Surat Peringatan', 'Surat Peringatan'), ('Sertifikat Pelatihan', 'Sertifikat Pelatihan'), ('Sertifikat K3', 'Sertifikat K3'), ('BPJS', 'BPJS'), ('Medical Check Up', 'Medical Check Up'), ('Dokumen Legal', 'Dokumen Legal'), ('Rekrutmen', 'Rekrutmen'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
            ],
            options={
                'verbose_name': 'Dokumen HRD',
                'verbose_name_plural': 'Dokumen HRD',
            },
        ),
    ]
