# Generated by Django 6.0.5 on 2026-05-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumenhrd',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='dokumenhrd',
            name='pembuat',
        ),
        migrations.RemoveField(
            model_name='dokumenstaff',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='dokumenstaff',
            name='pembuat',
        ),
    ]
