# Generated by Django 5.2.14 on 2026-05-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dokumenhrd_kategori_remove_dokumenhrd_pembuat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenhrd',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori'),
        ),
    ]
