# Generated by Django 5.2.14 on 2026-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dokumenhrd_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
