# Generated by Django 5.2.14 on 2026-05-13 14:44

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kategori', models.CharField(max_length=10, unique=True)),
                ('nama_kategori', models.CharField(max_length=50)),
                ('level_urgensi', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id_catatan', models.AutoField(primary_key=True, serialize=False)),
                ('referensi_dokumen', models.CharField(max_length=20)),
                ('nama_pegawai', models.CharField(max_length=100)),
                ('jenis_aksi', models.CharField(max_length=50)),
                ('waktu_catatan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('nomor_lengkap', models.CharField(max_length=15)),
                ('kunci_otp', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('grup_pengguna', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DokumenHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_referensi', models.CharField(max_length=20, unique=True)),
                ('judul_dokumen', models.CharField(max_length=100)),
                ('file_lampiran', models.FileField(upload_to='dokumen/')),
                ('tanggal_berlaku', models.DateField()),
                ('tanggal_kedaluwarsa', models.DateField()),
                ('status_dokumen', models.CharField(default='Aktif', max_length=20)),
                ('departemen', models.CharField(default='HRD', max_length=50)),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DokumenFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_referensi', models.CharField(max_length=20, unique=True)),
                ('judul_dokumen', models.CharField(max_length=100)),
                ('file_lampiran', models.FileField(upload_to='dokumen/')),
                ('tanggal_berlaku', models.DateField()),
                ('tanggal_kedaluwarsa', models.DateField()),
                ('status_dokumen', models.CharField(default='Aktif', max_length=20)),
                ('departemen', models.CharField(default='Finance', max_length=50)),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
